baseurl = "https://blog.gainskills.top"
defaultContentLanguage = "en"
languageCode = "en-us"    #for RSS
metaDataFormat = "yaml"
enableEmoji = true
enableGitInfo = true
title = "Blog - uTIcARdI"   #title is required
theme = "hugo-theme-cleanwhite"
preserveTaxonomyNames = true
paginate = 9    #frontpage pagination
hasCJKLanguage = true
enableRobotsTXT = true
canonifyURLs = true
timeout = 30000
pluralizeListTitles = false
disableAliases = true

#publishDir = "docs"
staticDir = "assets"

# Google Analytics
googleAnalytics = "UA-131650010-2"
# Enable comments by entering your Disqus shortname
DisqusShortname = "kexian-zhangs-blog"

[outputs]
home = ["HTML", "RSS", "Algolia"]
section = [ "HTML", "RSS"]

[params]
  ### Note: the file name and url of posts should be in lowercase ###
  header_image = "img/home-psb-bg.jpeg"
  description = "Articles about Python, networking, servers and automation"
  keywords = "Network, Cisco, Linux, Python, Internet, Web, Cloud, Ansible, Automation, Integration, Windows, Server, Code, Open Source, Cloud, SaaS"
  slogan = "KISS"

  postimgfoler = "/img/postimgs" #full url: assertsDir + /img/postimgs
  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # Enable to show the github link of the templete author in footer
  showOrigin = false

  # Enable to show 'about me' tag in nav bar
  about_me = true

  # algolia site search
  algolia_search = true
  algolia_appId = "6WV9KOERD5"
  algolia_indexName = "KZ's Blog"
  algolia_apiKey = "594b31183399cb21eefbca88e3e3f820"

  # Sidebar settings
  sidebar_about_description = "Python Developer, Network Engineer, DevOps, Automation, Open Source Enthusiast"
  # sidebar_avatar = "img/avatar-kz.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 3
  friends = true
  bookmarks = true

  # Google Site ID - search.google.com
  ga_site_id = ""

  # Google AdSense - AD
  Google_ad_id = "ca-pub-5029900143451942"

  # Baidu Analytics
  ba_track_id = ""

  # Baidu TuiGuang
  ba_ad_id = ""

  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  # atleast one of infooter or insidebar must be true after social url was added
  infooter       = false  # show social icons in footer
  insidebar      = true   # show social icons below self introduction
  rss            = true
  linkedin       = ""
  stackoverflow  = "https://stackoverflow.com/users/2701959/69444091"
  email          = "kex_zh@outlook.com"
  github         = "https://github.com/gainskills"
  #zhihu         = "full profile url in facebook"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #weibo         = "full profile url in twitter"
  #instagram     = "full profile url in instagram"
  #wechat        = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  #medium        = "full profile url in medium"

  [[params.friend_link]]
  title = "Tom大叔"
  href =  "http://www.cnblogs.com/TomXu/"
  [[params.friend_link]]
  title = "CC的行摄日记"
  href =  "https://www.weibo.com/u/5941049491"

  [[params.bookmark_link]]
  title =  "EVE-NG"
  href =  "http://eve-ng.net/"
  [[params.bookmark_link]]
  title =  "Huabing's Blog"
  href =  "https://zhaohuabing.com"
  [[params.bookmark_link]]
  title =  "TUALATRIX's Blog"
  href =  "https://imtx.me/"
  [[params.bookmark_link]]
  title =  "技术改变世界-孔今贤的博客"
  href =  "https://lingxiankong.github.io"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup]
  [markup.blackFriday]
    fractions = false
  [markup.goldmark.renderer]
    unsafe = true
    xHTML = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 3

[blackfriday]
  hrefTargetBlank = true
  fractions = false
  nofollowLinks = true
  noreferrerLinks = true

[related]
threshold = 100
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 20
  anchor = "smart"

[sitemap]
  ChangeFreq = "weekly"
  Priority = 0.9

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
